
import { Feed } from './types';

export const INITIAL_FEEDS: Feed[] = [
  // Top National & Business
  { id: 'toi', url: 'https://timesofindia.indiatimes.com/rssfeedstopstories.cms', title: 'The Times of India', color: '#ea580c' },
  { id: 'ndtv', url: 'https://feeds.feedburner.com/ndtvnews-top-stories', title: 'NDTV', color: '#dc2626' },
  { id: 'indiatoday', url: 'https://www.indiatoday.in/rss/home', title: 'India Today', color: '#d97706' },
  { id: 'indianexpress', url: 'https://indianexpress.com/feed/', title: 'Indian Express', color: '#2563eb' },
  { id: 'thehindu_nat', url: 'https://www.thehindu.com/news/national/feeder/default.rss', title: 'The Hindu (National)', color: '#4f46e5' },
  { id: 'thehindu_all', url: 'https://www.thehindu.com/feeder/default.rss', title: 'The Hindu (All)', color: '#4338ca' },
  { id: 'hindustantimes', url: 'https://www.hindustantimes.com/feeds/rss/india-news/rssfeed.xml', title: 'Hindustan Times', color: '#0ea5e9' },
  { id: 'businessstandard', url: 'https://www.business-standard.com/rss/latest.rss', title: 'Business Standard', color: '#db2777' },
  { id: 'economictimes', url: 'https://economictimes.indiatimes.com/rssfeedsdefault.cms', title: 'Economic Times', color: '#be185d' },
  { id: 'dnaindia', url: 'https://www.dnaindia.com/feeds/latest.xml', title: 'DNA India', color: '#e11d48' },
  { id: 'firstpost', url: 'https://www.firstpost.com/rss', title: 'Firstpost', color: '#7c3aed' },
  { id: 'livemint', url: 'https://www.livemint.com/rss/news', title: 'LiveMint', color: '#059669' },
  { id: 'moneycontrol', url: 'https://www.moneycontrol.com/rss/MCtopnews.xml', title: 'Moneycontrol', color: '#16a34a' },
  { id: 'financialexpress', url: 'https://www.financialexpress.com/feed/', title: 'Financial Express', color: '#ca8a04' },
  { id: 'businesstoday', url: 'https://www.businesstoday.in/rss/home', title: 'Business Today', color: '#3b82f6' },
  { id: 'cnbctv18', url: 'https://www.cnbctv18.com/rss/india.xml', title: 'CNBC TV18', color: '#6366f1' },
  { id: 'bwbusinessworld', url: 'https://www.businessworld.in/rss.xml', title: 'BW BusinessWorld', color: '#8b5cf6' },
  { id: 'outlookbusiness', url: 'https://www.outlookbusiness.com/rss', title: 'Outlook Business', color: '#ec4899' },
  
  // Major News Networks
  { id: 'scroll', url: 'https://feeds.feedburner.com/ScrollinArticles.rss', title: 'Scroll.in', color: '#0e7490' },
  { id: 'thequint', url: 'https://www.thequint.com/feed', title: 'The Quint', color: '#a21caf' },
  { id: 'news18', url: 'https://www.news18.com/rss/india.xml', title: 'News18', color: '#f43f5e' },
  { id: 'abpnews', url: 'https://news.abplive.com/home/feed', title: 'ABP News', color: '#d946ef' },
  { id: 'republicworld', url: 'https://www.republicworld.com/rss/india-news.xml', title: 'Republic World', color: '#e11d48' },
  { id: 'zeenews', url: 'https://zeenews.india.com/rss/india-national-news.xml', title: 'Zee News', color: '#f59e0b' },
  { id: 'deccanchronicle', url: 'https://www.deccanchronicle.com/rss', title: 'Deccan Chronicle', color: '#14b8a6' },
  { id: 'deccanherald', url: 'https://www.deccanherald.com/rss/india.xml', title: 'Deccan Herald', color: '#06b6d4' },
  { id: 'theprint', url: 'https://theprint.in/feed/', title: 'The Print', color: '#3b82f6' },
  { id: 'thewire', url: 'https://thewire.in/feed', title: 'The Wire', color: '#ef4444' },
  { id: 'altnews', url: 'https://www.altnews.in/feed/', title: 'Alt News', color: '#84cc16' },
  { id: 'freepressjournal', url: 'https://www.freepressjournal.in/rss/top-stories', title: 'Free Press Journal', color: '#6366f1' },
  { id: 'tribuneindia', url: 'https://www.tribuneindia.com/feed', title: 'Tribune India', color: '#8b5cf6' },
  { id: 'asianage', url: 'https://www.asianage.com/rss_feed.xml', title: 'Asian Age', color: '#ec4899' },
  { id: 'outlookindia', url: 'https://www.outlookindia.com/rss/main', title: 'Outlook India', color: '#f43f5e' },
  { id: 'newindianexpress', url: 'https://www.newindianexpress.com/rss', title: 'The New Indian Express', color: '#d946ef' },
  { id: 'telegraphindia', url: 'https://www.telegraphindia.com/rss/india.xml', title: 'Telegraph India', color: '#e11d48' },
  { id: 'thestatesman', url: 'https://www.thestatesman.com/feed/', title: 'The Statesman', color: '#f59e0b' },
  { id: 'frontline', url: 'https://frontline.thehindu.com/feeder/default.rss', title: 'Frontline', color: '#14b8a6' },
  { id: 'indiatv', url: 'https://www.indiatvnews.com/rss/top-news.xml', title: 'India TV', color: '#06b6d4' },
  { id: 'newsclick', url: 'https://www.newsclick.in/rss.xml', title: 'NewsClick', color: '#3b82f6' },
  { id: 'organiser', url: 'https://organiser.org/feed/', title: 'Organiser', color: '#ef4444' },
  { id: 'thebetterindia', url: 'https://www.thebetterindia.com/feed/', title: 'The Better India', color: '#84cc16' },
  
  // Regional & Other
  { id: 'greaterkashmir', url: 'https://www.greaterkashmir.com/feed', title: 'Greater Kashmir', color: '#6366f1' },
  { id: 'risingkashmir', url: 'https://risingkashmir.com/feed', title: 'Rising Kashmir', color: '#8b5cf6' },
  { id: 'siasat', url: 'https://www.siasat.com/feed/', title: 'Siasat Daily', color: '#ec4899' },
  { id: 'patrika', url: 'https://www.patrika.com/rss/', title: 'Patrika', color: '#f43f5e' },
  { id: 'amarujala', url: 'https://www.amarujala.com/rss/breaking-news.xml', title: 'Amar Ujala', color: '#d946ef' },
  { id: 'navbharattimes', url: 'https://navbharattimes.indiatimes.com/rssfeedsdefault.cms', title: 'Navbharat Times', color: '#e11d48' },
  { id: 'dainikbhaskar', url: 'https://www.bhaskar.com/rss/', title: 'Dainik Bhaskar', color: '#f59e0b' },
  { id: 'aajtak', url: 'https://www.aajtak.in/rssfeeds/56.xml', title: 'Aaj Tak', color: '#14b8a6' },
  { id: 'jagran', url: 'https://rss.jagran.com/rss/news/national.xml', title: 'Jagran', color: '#06b6d4' },
  { id: 'oneindia', url: 'https://www.oneindia.com/rss/news-india.xml', title: 'OneIndia', color: '#3b82f6' },
  { id: 'rediff', url: 'https://www.rediff.com/rss/newsrss.xml', title: 'Rediff News', color: '#ef4444' },
  { id: 'aninews', url: 'https://aninews.in/rss/feed.aspx', title: 'ANI News', color: '#84cc16' },
  { id: 'socialsamosa', url: 'https://www.socialsamosa.com/feed/', title: 'Social Samosa', color: '#6366f1' },
  { id: 'kashmirobserver', url: 'https://kashmirobserver.net/feed/', title: 'Kashmir Observer', color: '#8b5cf6' },
  { id: 'assamtribune', url: 'https://assamtribune.com/feed', title: 'Assam Tribune', color: '#ec4899' },
  { id: 'sentinelassam', url: 'https://www.sentinelassam.com/rss.xml', title: 'Sentinel Assam', color: '#f43f5e' },
  { id: 'arunachaltimes', url: 'https://www.arunachaltimes.in/feed/', title: 'Arunachal Times', color: '#d946ef' },
  { id: 'sikkimexpress', url: 'https://www.sikkimexpress.com/feed', title: 'Sikkim Express', color: '#e11d48' },
  { id: 'telanganatoday', url: 'https://telanganatoday.com/feed/', title: 'Telangana Today', color: '#f59e0b' },
  { id: 'dailyexcelsior', url: 'https://www.dailyexcelsior.com/feed', title: 'Daily Excelsior', color: '#14b8a6' },
  { id: 'starofmysore', url: 'https://starofmysore.com/feed/', title: 'Star of Mysore', color: '#06b6d4' },
  { id: 'opindia', url: 'https://www.opindia.com/feed/', title: 'OpIndia', color: '#3b82f6' },
  { id: 'tfipost', url: 'https://tfipost.com/feed/', title: 'TFI Post', color: '#ef4444' },
  { id: 'newsblare', url: 'https://newsblare.com/feed/', title: 'NewsBlare', color: '#84cc16' },
  { id: 'knnindia', url: 'https://knnindia.co.in/newsfeed/feed.xml', title: 'KNN India', color: '#6366f1' },

  // Niche & Specific (Updated URLs)
  { id: 'storifynews', url: 'https://storifynews.com/feed', title: 'Storify News', color: '#65a30d' },
  { id: 'abcrnews', url: 'https://abcrnews.com/feed', title: 'AbcrNews', color: '#16a34a' },
  { id: 'odishabarta', url: 'https://odishabarta.com/feed', title: 'Odishabarta', color: '#0891b2' },
  { id: 'timesofbengal', url: 'https://thetimesofbengal.com/feed', title: 'Times of Bengal', color: '#0369a1' },
  { id: 'digpu', url: 'https://digpu.com/feed', title: 'Digpu', color: '#4338ca' },
  { id: 'agranews', url: 'https://agranews.com/feed/', title: 'Agra News', color: '#6d28d9' },
  { id: 'northlines', url: 'https://thenorthlines.com/feed', title: 'Northlines', color: '#be185d' },
  { id: 'chandigarhmetro', url: 'https://chandigarhmetro.com/feed/', title: 'Chandigarh Metro', color: '#be123c' },
  { id: 'crowdwisdom', url: 'https://crowdwisdom.live/feed', title: 'CrowdWisdom360', color: '#b91c1c' },
  { id: 'newstoday', url: 'https://newstodaynet.com/feed', title: 'News Today', color: '#c2410c' },
  { id: 'indiavision', url: 'https://indiavision.com/feed', title: 'IndiaVision', color: '#a16207' },
  { id: 'orissapost', url: 'https://orissapost.com/feed', title: 'OrissaPOST', color: '#15803d' },
  { id: 'vindhyafirst', url: 'https://vindhyafirst.com/feed', title: 'Vindhya First', color: '#047857' },
  { id: 'yovizag', url: 'https://yovizag.com/feed', title: 'Yo Vizag', color: '#0e7490' },
  { id: 'techgenyz', url: 'https://www.techgenyz.com/feed/', title: 'TechGenYZ', color: '#0369a1' },
  { id: 'kashmirnews', url: 'https://kashmirnews.in/feed/', title: 'Kashmir News', color: '#1d4ed8' },
  { id: 'hubnews', url: 'https://hubnetwork.in/feed', title: 'Hub News', color: '#7e22ce' },
  { id: 'theindiabizz', url: 'https://www.theindiabizz.com/feed', title: 'The India Bizz', color: '#a21caf' },
  { id: 'biovoice', url: 'https://www.biovoicenews.com/feed/', title: 'BioVoice News', color: '#be185d' },
  { id: 'apnlive', url: 'https://apnlive.com/feed', title: 'APN Live', color: '#be123c' },
  { id: 'bhaskarlive', url: 'https://bhaskarlive.in/feed', title: 'Bhaskar Live', color: '#881337' },
  { id: 'delhipost', url: 'https://delhipostnews.com/feed', title: 'Delhi Post', color: '#7f1d1d' },
  { id: 'pragativadi', url: 'https://pragativadi.com/feed', title: 'Pragativadi', color: '#9a3412' },
  { id: 'anewsofindia', url: 'https://anewsofindia.com/feed', title: 'A News Of India', color: '#d97706' },
  { id: 'indiaobservers', url: 'https://indiaobservers.com/feed', title: 'India Observers', color: '#a16207' },
  { id: 'startupreporter', url: 'https://startupreporter.in/feed', title: 'Startup Reporter', color: '#4d7c0f' },
  { id: 'thenewsmill', url: 'https://thenewsmill.com/feed', title: 'The News Mill', color: '#15803d' },
  { id: 'quintdaily', url: 'https://quintdaily.com/feed', title: 'QuintDaily', color: '#0e7490' },
  { id: 'telanganatribune', url: 'https://telanganatribune.com/feed', title: 'Telangana Tribune', color: '#0369a1' },
  { id: 'nationalherald', url: 'https://www.nationalheraldindia.com/rss', title: 'National Herald', color: '#1d4ed8' },
  { id: 'smarttechtoday', url: 'https://smarttechtoday.com/feed', title: 'Smart Tech Today', color: '#be123c' },
  { id: 'thenewshimachal', url: 'https://thenewshimachal.com/feed', title: 'The News Himachal', color: '#881337' },
  { id: 'bilkulonline', url: 'https://bilkulonline.com/feed', title: 'Bilkul Online', color: '#7f1d1d' },
  { id: 'assamtimes', url: 'https://assamtimes.org/rss.xml', title: 'Assam Times', color: '#b45309' }
];

export const PLACEHOLDER_IMAGE = "https://picsum.photos/600/400";

export const STOP_WORDS = new Set([
  'a', 'an', 'the', 'and', 'or', 'but', 'is', 'are', 'was', 'were', 'in', 'on', 'at', 'to', 'for', 'of', 'with', 'by', 
  'from', 'up', 'down', 'about', 'into', 'over', 'after', 'new', 'news', 'update', 'latest', 'today', 'daily', 'live', 
  'breaking', 'top', 'best', 'review', 'guide', 'how', 'what', 'why', 'when', 'where', 'who', 'which', 'this', 'that', 
  'these', 'those', 'it', 'its', 'he', 'she', 'they', 'them', 'his', 'her', 'their', 'i', 'we', 'you', 'me', 'us', 
  'my', 'your', 'be', 'been', 'being', 'have', 'has', 'had', 'do', 'does', 'did', 'will', 'would', 'shall', 'should', 
  'can', 'could', 'may', 'might', 'must', 'rss', 'feed', 'click', 'here', 'read', 'more', 'copyright', 'rights', 
  'reserved', 'india', 'indian', 'say', 'says', 'said', 'video', 'watch', 'photos', 'images', 'pics', 'full', 'story',
  'govt', 'government', 'state', 'central', 'politic', 'politics', 'report', 'reports', 'amid', 'over', 'near', 'case',
  'police', 'court', 'high', 'supreme', 'year', 'month', 'week', 'day', 'time', '2023', '2024', '2025'
]);
